version: '3.8'
services:
  inventree-db:
    image: 'postgres:13'
    container_name: inventree-db
    expose:
      - '${INVENTREE_DB_PORT:-5432}/tcp'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdb
      - "POSTGRES_USER=${INVENTREE_DB_USER:?You must provide the 'INVENTREE_DB_USER' variable in the .env file}"
      - "POSTGRES_PASSWORD=${INVENTREE_DB_PASSWORD:?You must provide the 'INVENTREE_DB_PASSWORD' variable in the .env file}"
      - "POSTGRES_DB=${INVENTREE_DB_NAME:?You must provide the 'INVENTREE_DB_NAME' variable in the .env file}"
    volumes:
      - "inventree_data:/var/lib/postgresql/data/:z"
    restart: unless-stopped
  inventree-server:
    image: 'inventree/inventree:latest'
    container_name: inventree-server
    expose:
      - 8000
    depends_on:
      - inventree-db
    environment:
      INVENTREE_DEBUG: '${INVENTREE_DEBUG}'
      INVENTREE_LOG_LEVEL: '${INVENTREE_LOG_LEVEL}'
      INVENTREE_ADMIN_USER: '${INVENTREE_ADMIN_USER}'
      INVENTREE_ADMIN_PASSWORD: '${INVENTREE_ADMIN_PASSWORD}'
      INVENTREE_ADMIN_EMAIL: '${INVENTREE_ADMIN_EMAIL}'
      INVENTREE_DB_ENGINE: '${INVENTREE_DB_ENGINE}'
      INVENTREE_DB_NAME: '${INVENTREE_DB_NAME}'
      INVENTREE_DB_HOST: '${INVENTREE_DB_HOST}'
      INVENTREE_DB_PORT: '${INVENTREE_DB_PORT}'
      INVENTREE_DB_USER: '${INVENTREE_DB_USER}'
      INVENTREE_DB_PASSWORD: '${INVENTREE_DB_PASSWORD}'
      INVENTREE_PLUGINS_ENABLED: '${INVENTREE_PLUGINS_ENABLED}'
      INVENTREE_AUTO_UPDATE: '${INVENTREE_AUTO_UPDATE}'
      INVENTREE_SITE_URL: '${INVENTREE_SITE_URL}'
    volumes:
      - 'inventree_data:/home/inventree/data:z'
    restart: unless-stopped
  inventree-worker:
    image: 'inventree/inventree:${INVENTREE_TAG:-stable}'
    container_name: inventree-worker
    command: 'invoke worker'
    depends_on:
      - inventree-server
    environment:
      INVENTREE_DEBUG: '${INVENTREE_DEBUG}'
      INVENTREE_LOG_LEVEL: '${INVENTREE_LOG_LEVEL}'
      INVENTREE_DB_ENGINE: '${INVENTREE_DB_ENGINE}'
      INVENTREE_DB_NAME: '${INVENTREE_DB_NAME}'
      INVENTREE_DB_HOST: '${INVENTREE_DB_HOST}'
      INVENTREE_DB_PORT: '${INVENTREE_DB_PORT}'
      INVENTREE_DB_USER: '${INVENTREE_DB_USER}'
      INVENTREE_DB_PASSWORD: '${INVENTREE_DB_PASSWORD}'
      INVENTREE_SITE_URL: '${INVENTREE_SITE_URL}'
    volumes:
      - 'inventree_data:/home/inventree/data:z'
    restart: unless-stopped
  inventree-proxy:
    container_name: inventree-proxy
    image: 'caddy:alpine'
    restart: always
    depends_on:
      - inventree-server
    expose:
      - '${INVENTREE_WEB_PORT:-80}:80'
    environment:
      INVENTREE_DEBUG: '${INVENTREE_DEBUG}'
      INVENTREE_LOG_LEVEL: '${INVENTREE_LOG_LEVEL}'
      INVENTREE_DB_PASSWORD: '${INVENTREE_DB_PASSWORD}'
      INVENTREE_PLUGINS_ENABLED: '${INVENTREE_PLUGINS_ENABLED}'
      INVENTREE_AUTO_UPDATE: '${INVENTREE_AUTO_UPDATE}'
      INVENTREE_SITE_URL: '${INVENTREE_SITE_URL}'
    volumes:
      - './Caddyfile:/etc/caddy/Caddyfile:ro,z'
      - 'inventree_static:/var/www/static:z'
      - 'inventree_media:/var/www/media:z'
      - 'inventree_data:/var/log:z'
      - 'inventree_data:/data:z'
      - 'inventree_data:/config:z'

volumes:
  inventree_data:
  inventree_static:
  inventree_media:
